/**
 * Error codes for SPM (Skills Package Manager)
 * Inspired by pnpm's error code system
 */
export enum ErrorCode {
  // File system errors (1xx)
  FILE_NOT_FOUND = 'ENOENT',
  PERMISSION_DENIED = 'EACCES',
  FILE_EXISTS = 'EEXIST',
  FS_ERROR = 'EFS',

  // Git errors (2xx)
  GIT_CLONE_FAILED = 'EGITCLONE',
  GIT_FETCH_FAILED = 'EGITFETCH',
  GIT_CHECKOUT_FAILED = 'EGITCHECKOUT',
  GIT_REF_NOT_FOUND = 'EGITREF',
  GIT_NOT_INSTALLED = 'EGITNOTFOUND',

  // Parse errors (3xx)
  PARSE_ERROR = 'EPARSE',
  JSON_PARSE_ERROR = 'EJSONPARSE',
  YAML_PARSE_ERROR = 'EYAMLPARSE',
  INVALID_SPECIFIER = 'EINVALIDSPEC',

  // Config/Manifest errors (4xx)
  MANIFEST_NOT_FOUND = 'EMANIFEST',
  LOCKFILE_NOT_FOUND = 'ELOCKFILE',
  LOCKFILE_OUTDATED = 'ELOCKOUTDATED',
  MANIFEST_EXISTS = 'EMANIFESTEXISTS',

  // Network/Remote errors (5xx)
  NETWORK_ERROR = 'ENETWORK',
  REPO_NOT_FOUND = 'EREPONOTFOUND',

  // General errors (9xx)
  UNKNOWN_ERROR = 'EUNKNOWN',
  NOT_IMPLEMENTED = 'ENOTIMPL',
  VALIDATION_ERROR = 'EVALIDATION',
  SKILL_NOT_FOUND = 'ESKILLNOTFOUND',
  SKILL_EXISTS = 'ESKILLEXISTS',
}
